export enum RestAPI {
  AUTH = 'auth',
  COMMENT = 'comment',
  ITEM = 'item',
  FAV_TABLE = 'fav-table',
  FLOORPLAN = 'floorplan',
  LOCATION = 'location',
  ORDER = 'order',
  ORDER_COMMENT = 'order-comment',
  ORDER_ITEM = 'order-item',
  STATION = 'station',
  TABLE = 'table',
  TYPE = 'type',
  USER = 'user',
}
