version: '3'
services:
    nginx:
        # build: 
        #     context: .
        #     dockerfile: nginx/Dockerfile
        image: ordermanager/nginx
        depends_on:
            - server
            - client
        ports: 
            - "80:80"
            - "443:443"
    client:
        # build: 
        #     context: .
        #     dockerfile: client/Dockerfile
        image: ordermanager/client
        depends_on:
            - server
        ports: 
            - "8080:8080"
    server:
        # build: 
        #     context: .
        #     dockerfile: server/Dockerfile
        image: ordermanager/server
        environment:
            - OM_MONGODB_URL=mongodb://172.26.8.244:27017/
            - OM_MONGODB_NAME=order-manager
            - OM_SERVER_PORT=3001
        depends_on:
            - mongodb
        ports: 
            - "3001:3001"
    mongodb:
        image: mongo
        # image: antsman/rpi-mongodb
        volumes:
            - /srv/mongodb/data:/data/db
        ports: 
            - "27017:27017"
