version: '3'
services:
  nginx:
    image: ordermanager/nginx-rpi
    depends_on:
      - server
      - client
    ports:
      - '80:80'
      - '443:443'
  client:
    image: ordermanager/client
    depends_on:
      - server
    ports:
      - '8080:8080'
  server:
    image: ordermanager/server
    environment:
      - OM_MONGODB_URL=172.26.5.236:27017/
      - OM_MONGODB_NAME=order-manager-aws
      - OM_MONGODB_USER=om
      - OM_MONGODB_PASSWORD=order-manager
      - OM_SERVER_PORT=3001
    depends_on:
      - mongodb
    ports:
      - '3001:3001'
  mongodb:
    image: antsman/rpi-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=om
      - MONGO_INITDB_ROOT_PASSWORD=order-manager
    volumes:
      - /srv/mongodb/data:/data/db
    ports:
      - '27017:27017'
