FROM tobi312/rpi-nginx

RUN apt update && apt install wget

COPY nginx/etc/nginx/conf.d/* /etc/nginx/conf.d/
COPY nginx/etc/nginx/ssl/* /etc/nginx/ssl/
COPY nginx/etc/nginx/nginx.conf /etc/nginx/
COPY nginx/etc/nginx/redirect-map.conf /etc/nginx/

ARG WORK_DIR=/home/node/om/client

WORKDIR ${WORK_DIR}

COPY client/deploy/* /srv/om/

RUN wget https://dl.eff.org/certbot-auto
RUN mv certbot-auto /usr/local/bin/certbot-auto
RUN chown root /usr/local/bin/certbot-auto
RUN chmod 0755 /usr/local/bin/certbot-auto

# RUN /usr/local/bin/certbot-auto certonly --nginx

# ENTRYPOINT [ "/usr/bin/entry.sh", "nginx", "-g", "daemon off;" ]