version: '3'
services:
    server:
        build: 
            context: .
            dockerfile: server/Dockerfile
        image: om-server
        environment:
            - OM_MONGODB_URL=mongodb://3.214.197.198:27017/
            - OM_MONGODB_NAME=order-manager
            - OM_SERVER_PORT=3001
        depends_on:
            - mongodb
        entrypoint: 
            - "yarn"
            - "run"
            - "startServer"
        networks:
            om:
                ipv4_address: 172.16.238.10
                aliases:
                    - om-server
        ports: 
            - "3001:3001"
    nginx:
        build: 
            context: .
            dockerfile: nginx/Dockerfile
        image: om-nginx
        depends_on:
            - server
        networks:
            om:
                ipv4_address: 172.16.238.20
                aliases:
                    - om-nginx
        ports: 
            - "80:80"
            - "443:443"
    mongodb:
        image: mongo
        # image: antsman/rpi-mongodb
        networks:
            om:
                ipv4_address: 172.16.238.30
                aliases:
                    - om-mongodb
        ports: 
            - "27017:27017"

networks:
    om:
        ipam:
            driver: default
            config:
              - subnet: "172.16.238.0/24"
